#include "TileMap.h"

String TileMap[H] = {

	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"B                                                                              B",
	"B                                                                              B",
	"B                                                                              B",
	"B                                                                              B",
	"B                                                                              B",
	"B                                 O                    O                       B",
	"B                       O                                                      B",
	"B            O                               O                                 B",
	"B                                                                  O           B",
	"B   O                                                                          B",
	"B                                                                              B",
	"B       A      A   A      A     A           A       A   A             O        B",
	"B                                     5                                        B",
	"B                                                                              B",
	"B      BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB       O     B",
	"B      B               B                                   B                   B",
	"B      B               B   W                    W          B                   B",
	"B     BB               B              P                    B                   B",
	"B      f               e                                   d           O       B",
	"BB     b           H   b                                   b                   B",
	"B      b               b         C   C   C   N             b                   B",
	"B      b  4   S        b   3                               b                   B",
	"B      b               b                                   b  2                B",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                   B",
	"B                         B                                BBBBBBB             B",
	"B              W          B                        W       BBBBBBBB            B",
	"B                         B                P               B                   B",
	"B       P                 a                                c                   B",
	"B                         b   H   T                        b           BB      B",
	"B  C                      b               C   N            b           BB      B",
	"B         S           0   b                        S    1  b           BB      B",
	"B                         b                                b           BB      B",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",

};

